name: digital_currency
description: List of digital currency, the current day in real time and the balance of the last two weeks
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  dartz: ^0.10.0  
  flutter:
    sdk: flutter

 
dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.1.4
  very_good_analysis: ^2.3.0

flutter:
